### ISSUE TITLE
the tourl function should be made compatible with auto-escaping

### ISSUE THREAD

**Issue by stof** [thecodingmachine/html.renderer.twig-extensions#16]
This function is meant to return some HTML. However, it does not mark itself as safe, and does not escape things to actually be safe.

and btw, the implementation is fragile. You may want to use https://github.com/iamcal/lib_autolink/ instead.

**Comment by moufmouf** [comment]
I'll simply deprecate it (See #17). This function should never have been here in the first place, and I'm pretty sure it's almost not used.
I should only put in this extension functions that are directly related to the Mouf framework, not utility functions.

**Comment by stof** [comment]
> I should only put in this extension functions that are directly related to the Mouf framework, not utility functions.

totally agree with that
